=== AnonymerNiklasistanonym/UniStats/templates/uni_template.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "definitions": {
        "module": {
            "additionalProperties": false,
            "description": "A module/Ein Modul",
            "properties": {
                "credits": {
                    "description": "ETCS credits/ETCS Credits",
                    "type": "integer"
                },
                "oral_exam": {
                    "description": "Did you participate in an oral exam because of you had not any exam tries left?/Hast du an einer mündlichen Prüfung teilgenommen weil du keine Klausurversuche mehr hattest?",
                    "type": "boolean"
                },
                "grade": {
                    "description": "Module or exam grade/Modul- oder Klausurnote",
                    "type": "number"
                },
                "name": {
                    "description": "Module name/Modulname",
                    "type": "string"
                },
                "number": {
                    "description": "Module number/Modulnummer",
                    "type": "number"
                },
                "participated_semesters": {
                    "description": "List of all semesters you participated this course/Liste an Semestern in welchen du dieses Modul besucht hast",
                    "items": {
                        "type": "integer"
                    },
                    "uniqueItems": true,
                    "type": "array"
                },
                "recommended_semester": {
                    "description": "The recommended semester/Das empfohlene Semester",
                    "type": "integer"
                },
                "weighting_factor": {
                    "description": "The weighting factor of the grade/Der Gewichtungsfaktor für die Note",
                    "type": "number"
                },
                "wrote_exam_semesters": {
                    "description": "A list of all semesters you wrote the exam/Eine Liste von allen Semestern in welchen du die Klausur geschrieben hast",
                    "items": {
                        "type": "integer"
                    },
                    "uniqueItems": true,
                    "type": "array"
                }
            },
            "required": [
                "name",
                "number",
                "credits"
            ],
            "type": "object"
        },
        "catalog": {
            "additionalProperties": false,
            "description": "A catalog/Ein Katalog",
            "properties": {
                "credits": {
                    "description": "The minimum ETCS credits you need from this catalog/Die kleinste Anzahl an ETCS credits welche man in diesem Katalog besitzen muss",
                    "type": "integer"
                },
                "name": {
                    "description": "Catalog name/Katalogname",
                    "type": "string"
                },
                "number": {
                    "description": "Catalog number/Katalognummer",
                    "type": "number"
                },
                "modules": {
                    "description": "Catalog modules/Katalogmodule",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/module"
                    }
                }
            },
            "required": [
                "name",
                "number",
                "credits"
            ],
            "type": "object"
        }
    },
    "properties": {
        "$schema": {
            "description": "Pointer to the schema against which this document should be validated/Zeiger zu dem verwendeten Dokument welches nach diesem validiert werden soll",
            "title": "Schema",
            "type": "string"
        },
        "current_semester": {
            "description": "Your current semeser/Dein aktuelles Semester",
            "type": "integer"
        },
        "title": {
            "description": "The title of the document/Titel des Dokuments",
            "type": "string"
        },
        "start_year": {
            "additionalProperties": false,
            "description": "Your start year/Dein Startjahr",
            "required": ["year", "semester"],
            "properties": {
                "year": {
                    "description": "Your start year/Dein Startjahr",
                    "type": "integer"
                },
                "semester": {
                    "description": "Your start semester/Dein Startsemester",
                    "type": "string",
                    "enum": ["WS", "SS"]
                }
            }
        },
        "field_of_study": {
            "description": "Your field of study/Dein Studiengang bzw. -fach",
            "type": "string"
        },
        "matriculation_number": {
            "description": "The matriculation_number/Die Matrikelnummer",
            "type": "integer"
        },
        "modules": {
            "additionalProperties": false,
            "description": "Your modules/Deine Module",
            "properties": {
                "base": {
                    "uniqueItems": true,
                    "description": "Your base modules/Deine Basismodule",
                    "items": {
                        "$ref": "#/definitions/module"
                    },
                    "type": "array"
                },
                "core": {
                    "description": "Your core modules/Deine Kernmodule",
                    "uniqueItems": true,
                    "items": {
                        "$ref": "#/definitions/module"
                    },
                    "type": "array"
                },
                "key_qualifications": {
                    "description": "Your key_qualifications/Deine Schlüsselqualifikationen",
                    "uniqueItems": true,
                    "items": {
                        "$ref": "#/definitions/module"
                    },
                    "type": "array"
                },
                "supplementary": {
                    "description": "Your supplementary modules/Deine Ergänzungsmodule",
                    "uniqueItems": true,
                    "items": {
                        "$ref": "#/definitions/catalog"
                    },
                    "type": "array"
                }
            },
            "required": [
                "base",
                "core",
                "supplementary",
                "key_qualifications"
            ],
            "type": "object"
        },
        "name": {
            "additionalProperties": false,
            "description": "Your name/Dein Name",
            "properties": {
                "first_name": {
                    "description": "Your first_name/Dein Vorname",
                    "type": "string"
                },
                "surname": {
                    "description": "Your surname/Dein Nachname",
                    "type": "string"
                }
            },
            "required": [
                "first_name",
                "surname"
            ],
            "type": "object"
        },
        "needed_credits": {
            "description": "The needed ETCS credits/Die zu erreichenden ETCS Credits",
            "type": "integer"
        }
    },
    "required": [
        "matriculation_number",
        "current_semester",
        "field_of_study",
        "name",
        "start_year",
        "title",
        "needed_credits"
    ],
    "type": "object"
}

=== AnonymerNiklasistanonym/UniStats/data/demo.json
{
    "$schema": "../templates/uni_template.json",
    "field_of_study": "Medieninformatik",
    "matriculation_number": 123456,
    "name": {
        "first_name": "Your",
        "surname": "Name"
    },
    "current_semester": 5,
    "needed_credits": 180,
    "title": "Bachelor Medieninformatik",
    "start_year": {
        "year": 2016,
        "semester": "WS"
    },
    "modules": {
        "base": [
            {
                "name": "Programmierung und Software-Entwicklung",
                "number": 10281,
                "credits": 9,
                "participated_semesters": [
                    1,
                    2
                ],
                "wrote_exam_semesters": [
                    1,
                    2
                ],
                "recommended_semester": 1,
                "grade": 2.0
            },
            {
                "name": "Mathematik f端r Informatiker und Softwaretechniker",
                "number": 10190,
                "credits": 18,
                "recommended_semester": 2,
                "participated_semesters": [
                    1,
                    2
                ],
                "wrote_exam_semesters": [
                    2
                ]
            },
            {
                "name": "Mensch-Computer-Interaktion",
                "number": 10210,
                "credits": 6,
                "participated_semesters": [
                    2
                ],
                "wrote_exam_semesters": [
                    2
                ],
                "recommended_semester": 2,
                "grade": 3.7
            },
            {
                "name": "Theoretische Grundlagen der Informatik",
                "number": 10940,
                "credits": 12,
                "participated_semesters": [
                    1,
                    2,
                    3,
                    4,
                    5
                ],
                "wrote_exam_semesters": [
                    5
                ],
                "recommended_semester": 2
            },
            {
                "name": "Datenstrukturen und Algorithmen",
                "number": 12060,
                "credits": 9,
                "participated_semesters": [
                    2
                ],
                "wrote_exam_semesters": [
                    2
                ],
                "recommended_semester": 2,
                "grade": 1.7
            },
            {
                "name": "Medieninformatik",
                "number": 56210,
                "credits": 6,
                "participated_semesters": [
                    1
                ],
                "wrote_exam_semesters": [
                    1
                ],
                "recommended_semester": 1,
                "grade": 1.0
            }
        ],
        "core": [
            {
                "name": "Computergraphik",
                "number": 10060,
                "credits": 6,
                "participated_semesters": [
                    5
                ],
                "wrote_exam_semesters": [
                    5
                ],
                "recommended_semester": 5,
                "grade": 3.7
            },
            {
                "name": "Imaging Science",
                "number": 10170,
                "credits": 6,
                "participated_semesters": [
                    4
                ],
                "wrote_exam_semesters": [
                    4
                ],
                "recommended_semester": 4,
                "grade": 2.7
            },
            {
                "name": "Programmierung f端r Medieninformatik",
                "number": 56220,
                "credits": 6,
                "participated_semesters": [
                    3
                ],
                "recommended_semester": 3,
                "grade": 3.7
            },
            {
                "name": "Empirische Methoden f端r Medieninformatik",
                "number": 56320,
                "credits": 6,
                "participated_semesters": [
                    3,
                    5
                ],
                "recommended_semester": 3
            },
            {
                "name": "Medieninformatik Projekt - Theorie",
                "number": 56240,
                "credits": 6,
                "recommended_semester": 4
            },
            {
                "name": "Seminar Medieninformatik",
                "number": 56250,
                "credits": 6,
                "recommended_semester": 5
            },
            {
                "name": "Fachstudie Medieninformatik",
                "number": 56260,
                "credits": 6,
                "recommended_semester": 6
            }
        ],
        "supplementary": [
            {
                "name": "INF",
                "number": 310,
                "credits": 18,
                "modules": [
                    {
                        "name": "Programmierparadigmen",
                        "number": 36100,
                        "credits": 6,
                        "participated_semesters": [
                            4
                        ],
                        "wrote_exam_semesters": [
                            4
                        ],
                        "recommended_semester": 4,
                        "grade": 3.0
                    },
                    {
                        "name": "Systemkonzepte und -programmierung",
                        "number": 40090,
                        "credits": 6,
                        "participated_semesters": [
                            3
                        ],
                        "wrote_exam_semesters": [
                            3
                        ],
                        "recommended_semester": 5,
                        "grade": 2.8
                    }
                ]
            },
            {
                "name": "MIG",
                "number": 320,
                "credits": 18,
                "modules": [
                    {
                        "name": "Einf端hrung in die Technische Informatik",
                        "number": 14360,
                        "credits": 6,
                        "participated_semesters": [
                            3
                        ],
                        "wrote_exam_semesters": [
                            3
                        ],
                        "recommended_semester": 3,
                        "grade": 1.7
                    },
                    {
                        "name": "Programmentwicklung",
                        "number": 14390,
                        "credits": 6,
                        "participated_semesters": [
                            3,
                            4
                        ],
                        "wrote_exam_semesters": [
                            3,
                            4
                        ],
                        "recommended_semester": 3,
                        "grade": 3.3
                    }
                ]
            }
        ],
        "key_qualifications": [
            {
                "name": "Medieninformatik Projekt - Praktikum",
                "number": 56271,
                "credits": 15
            },
            {
                "name": "English for Computer Science (C1)",
                "number": 932830,
                "credits": 3,
                "participated_semesters": [
                    3
                ],
                "wrote_exam_semesters": [
                    3
                ],
                "grade": 3.0
            }
        ]
    }
}
